chore: add file type validation using python-magic
acesso-io/techcore-cvat pull request #100
Opened 2021-12-15 20:50 UTC by vinicius-nogueira

Restringir os possíveis tipos de arquivos que podem ser enviados para o CVAT na criação dos lotes.

[Jira](https://unicoidtech.atlassian.net/browse/CLIV-31):

> Validar o tipo de arquivo enviado na rota api/v1/tasks/<id>/data. Só poderão ser enviados arquivos do tipo PNG e zip
> 
> Informações complementares
> 
> - Arquivo:
> Controller(TaskViewSet.data) => apps/engine/views.py:413
> Serializer(DataSerializer) => apps/engine/serializers.py:268
> 
> - Rota => api/v1/tasks/<id>/data
> 
> - Mime type permitidos:
> image/jpeg
> image/png
> application/zip
> application/octet-stream
> application/x-zip-compressed
> multipart/x-zip

Issue #57

2021-12-15 21:09 UTC, vinicius-nogueira commented
Criei o `validators.py` só pra poder testar na minha máquina, mas fiquei na dúvida de onde faz mais sentido colocá-lo, em `views.py` mesmo?

O lugar onde chamei a classe de validação `FileMimeValidator()`, em `models.ClientFile`, tá correto?

O dict `ext_cnt_mapping` ainda está faltando alguns mime types dos propostos na tarefa, no próximo commit subo as alterações dele.

Quais outras alterações serão interessantes de fazer pra atender essa tarefa?

2021-12-17 12:46 UTC, vinicius-nogueira commented
- Criei o arquivo validators.py contendo a lógica de validação pelos MIME types, mas fiquei na dúvida de onde faz mais sentido colocá-lo, se a proposta do novo arquivo não for interessante.

- Pra rodar a interface do CVAT preciso estar conectado na vpn e acessar por uma aba anônima, coisa que antes não precisava. Está correto isso? Deve ser porque fiz o merge das alterações da develop pro meu branch.

- A validação do upload de pdf que achei que estava funcionando, na verdade não estava porque eu estava testando com dois arquivos pdf e já existe uma validação pra isso no sistema, que aceita apenas um arquivo pdf.

- Essa validação pré-existente está em (_validate_data) **cvat/apps/engine/task.py**.

- Quais outras alterações serão necessárias pra atender essa tarefa?

2021-12-20 20:57 UTC, hs-pedro commented on cvat/apps/engine/validators.py
> +    ext_cnt_mapping = {
o que seria o nome dessa variável?

2021-12-20 20:57 UTC, hs-pedro commented on cvat/apps/engine/validators.py
> +        if extension not in self.allowed_extensions:
Esse check poderia ser feito direto no dicionário. O `in` por padrão já checa se a key está presente no dict:
```python
if extension not in self.ext_cnf_mapping:
```

2021-12-20 20:57 UTC, hs-pedro commented on cvat/apps/engine/validators.py
> +                    'allowed_extensions': ', '.join(self.allowed_extensions)
aqui poderia ser só um `'allowed_extensions': ', '.join(self.ext_cnf_mapping.keys())`

2021-12-20 20:57 UTC, hs-pedro commented on cvat/apps/engine/validators.py
> +        )
Acho que não precisamos desse operador pra comparar instâncias do validador

2021-12-21 12:55 UTC, vinicius-nogueira commented on cvat/apps/engine/validators.py
> +    ext_cnt_mapping = {
Extension content mapping, mas já foi alterada para `DEFAULT_CNT_EXT_MAPPING` por sugestão do Gabriel, que me explicou que por se tratar de uma constante usamos uppercase, messages e code também serão alteradas.

2021-12-21 13:01 UTC, vinicius-nogueira commented on cvat/apps/engine/validators.py
> +        if extension not in self.allowed_extensions:
Entendi, mas aí aquele `__init__` não faz mais sentido, certo? Porque é ele que joga as keys do dicionário em uma lista.

2021-12-21 13:02 UTC, vinicius-nogueira commented on cvat/apps/engine/validators.py
> +        )
Boa, essa função já foi removida no último commit.

2021-12-21 17:30 UTC, vinicius-nogueira commented on cvat/apps/engine/validators.py
> +                    'allowed_extensions': ', '.join(self.allowed_extensions)
Alterado e removido o `__init__`!

2021-12-21 17:31 UTC, vinicius-nogueira commented on cvat/apps/engine/validators.py
> +        if extension not in self.allowed_extensions:
Removido o `__init__` da classe.

2021-12-21 21:25 UTC, hs-pedro requested changes

2021-12-21 21:25 UTC, hs-pedro commented on cvat/apps/engine/validators.py
> +        content_type = magic.from_buffer(data.read(1024), mime=True)
podemos mover essa chamada pra depois do `if extension`, dai ganhamos um tempo sem abrir o arquivo se a extensão já não for permitida

2021-12-21 21:25 UTC, hs-pedro commented on cvat/apps/engine/validators.py
> +        'jpg': 'image/jpg',
O mime type do `jpg` é `image/jpeg`

2021-12-21 21:25 UTC, hs-pedro commented on cvat/apps/engine/validators.py
> +        'x-zip': 'multipart/x-zip'
A gente quer receber ZIP como arquivo? Acho que podemos ser bem estritos e receber só imagens

2022-01-06 11:43 UTC, hs-pedro approved these changes

2022-01-14 13:27 UTC, hs-pedro commented on cvat/apps/engine/tests/test_rest_api.py
> +    def test_pdf_extension(self):
O nome do teste pode conter o comportamento esperado:  `test_return_error_on_pdf_extension`
Logo, se alguém precisar mudar esse teste fica claro que o comportamente deve ser retornar erro (regra de negócio) pra esse tipo de arquivo.

2022-01-14 13:27 UTC, hs-pedro commented on cvat/apps/engine/tests/test_rest_api.py
> +    def test_content_file(self):
Mesma coisa aqui. A ideia do teste é mandar um arquivo com extensão `.png` mas que o conteúdo é PDF? Poderia ser algo como `test_return_error_when_content_is_pdf`

2022-01-14 13:40 UTC, hs-pedro approved these changes

2022-01-14 20:27 UTC, vinicius-nogueira commented
- [ ] Testes unitários;

- [ ] Teste de upload de imagens/vídeos permitidos;

- [ ] Teste de upload de imagens/vídeos não permitidos;

- [ ] Teste de extensão de arquivo != mime type;

2022-01-14 20:35 UTC, vinicius-nogueira reviewed
Revisado.

2022-01-14 20:36 UTC, merged