[CAP-3] Configurar o pre-commit
acesso-io/techcore-cvat pull request #137
Opened 2022-01-31 14:00 UTC by vinicius-nogueira

[WIP]

2022-02-02 13:20 UTC, hspedro commented
Acho que vale uma explicação, talvez no README.md ou algum outro canto, sobre o que roda no pre-commit. Explicar que tem a necessidade de instalar o pacote do pre-commit também.

O projeto hoje já tem uma ferramenta, [husky](https://typicode.github.io/husky), pra gerenciar hooks do git. Ao meu ver poderiamos usar ou uma ou outra, já que ambas podem executar scripts shell pra validação

2022-02-08 19:38 UTC, vinicius-nogueira commented
**Reviewers**

Dêem uma olhada nos pontos seguintes:

1. Nos hooks configurados no arquivo `.pre-commit-config.yaml`, na ordem deles, se precisamos de mais hooks e se estão validando somente as alterações de código (default).
2. Na proposta que fiz de pre-push, subi neste PR o arquivo template `pre-push`, gerado automaticamente pela ferramenta Pre-Commit, o qual editei para rodar os testes unitários com o `make` antes de realizar o `git push`.

2022-02-08 19:38 UTC, vinicius-nogueira commented
> Acho que vale uma explicação, talvez no README.md ou algum outro canto, sobre o que roda no pre-commit e como instalar os hooks.
> 
> O projeto hoje já tem uma ferramenta, [husky](https://typicode.github.io/husky), pra gerenciar hooks do git. Ao meu ver poderiamos usar ou uma ou outra, já que ambas podem executar scripts shell pra validação

2022-02-09 17:21 UTC, GabrielRocha commented on CONTRIBUTING.md
> +    ```
Acho que seria uma boa colocar esses steps no Makefile, parecido com o que foi feito para o `copy`

2022-02-09 17:27 UTC, GabrielRocha requested changes

2022-02-09 17:27 UTC, GabrielRocha commented on pre.push
> +#!/usr/bin/env bash
Tem um typo no nome do arquivo., teria que ser`pre-push`. 
Recomendo criar uma pasta chamada **hooks** e colocar esse arquivo lá para ficar mais organizado.

2022-02-09 17:29 UTC, GabrielRocha commented on package.json
>      "eslint-plugin-header": "^3.1.0",
@hspedro 
Podemos remover esse arquivo, já que ele só é utilizado para configurar o lint?

2022-02-09 17:37 UTC, GabrielRocha requested changes

2022-02-09 17:37 UTC, GabrielRocha commented on pre.push
> +# ID: 138fd403232d2ddd5efb44317e38bf03
Precisa adicionar a permissão de execução nesse script
```shell
chmod +x pre-push
```

2022-02-09 17:37 UTC, GabrielRocha commented on Makefile
> +	fi
Esse comando precisa ser inline
```shell
copy-file:
	if [ -d ".git/hooks" ]; then cp -f hooks/pre-push .git/hooks; fi
```

2022-02-09 17:51 UTC, GabrielRocha requested changes

2022-02-09 17:51 UTC, GabrielRocha commented on pre.push
> +INSTALL_PYTHON=/home/vcosta/Downloads/generic_venv/bin/python3
O path está com as informações do usuário `vcosta`.

2022-02-09 18:10 UTC, vinicius-nogueira commented on CONTRIBUTING.md
> +    ```
A ideia é que esses comandos sejam rodados apenas uma vez, após o `git clone` do projeto, por exemplo; vou ver como viabilizar isso, talvez criando um novo comando `make`.

2022-02-09 18:30 UTC, vinicius-nogueira commented on pre.push
> +#!/usr/bin/env bash
Estava errado mesmo, mas subi uma nova proposta que não irá mais precisar desse arquivo, agora rodando um `make git-hooks` ele já cria automaticamente o arquivo `.git/hooks/pre-push` e `.git/hooks/pre-commit` com base no yaml.

2022-02-09 18:31 UTC, vinicius-nogueira commented on pre.push
> +# ID: 138fd403232d2ddd5efb44317e38bf03
Outdated.

Subi uma nova proposta sem ter que adicionar o arquivo `pre-push`.

2022-02-09 18:32 UTC, vinicius-nogueira commented on Makefile
> +	fi
Outdated.

Subi uma nova proposta sem ter que adicionar o arquivo `pre-push`.

2022-02-09 18:35 UTC, vinicius-nogueira commented on pre.push
> +INSTALL_PYTHON=/home/vcosta/Downloads/generic_venv/bin/python3
Outdated.

Sim, isso tava zuado.
Como esse arquivo é gerado automaticamente, subi uma nova proposta com um comando `make` que faz as configurações iniciais do `pre-push`.

2022-02-09 19:39 UTC, camilasonoda approved these changes

2022-02-09 19:49 UTC, vinicius-nogueira commented
Estou tomando esse erro ao final da execução do `git push`, após o teste unitário da api:
![image](https://user-images.githubusercontent.com/58186122/153278709-b3e41797-9c81-4b61-8c6f-a8d5bd800b10.png)

Será que tem como definir que o `exit code: 2` é o resultado de sucesso dos testes?

2022-02-10 13:17 UTC, GabrielRocha approved these changes

2022-02-10 13:37 UTC, vinicius-nogueira commented
@camilasonoda identificou que o erro nos testes do pre-push não bloqueiam a ação do `git push`, estou verificando essa questão.

2022-02-10 14:38 UTC, hspedro commented on package.json
>      "eslint-plugin-header": "^3.1.0",
Eu deixaria, porque pode ser que ele esteja sendo usado em alguma regra dos `.eslintrc.js` no repositório. A ideia é que o eslint do `pre-commit` vá rodar com as configs (`.eslintrc.js`) do projeto?

2022-02-10 23:18 UTC, vinicius-nogueira commented on package.json
>      "eslint-plugin-header": "^3.1.0",
Isso Pedro, posso estar errado mas não achei na documentação do Pre-Commit algo pra configurar as ferramentas dos hooks, pelo que vi podemos por exemplo configurar o `black` pelo .toml file do `Poetry`.

2022-02-11 14:17 UTC, camilasonoda approved these changes

2022-02-14 13:59 UTC, GabrielRocha approved these changes

2022-02-14 14:04 UTC, merged