Feat/add poetry - CAP-4
acesso-io/techcore-cvat pull request #138
Opened 2022-01-31 19:12 UTC by camilasonoda

Adicionei as dependências no pyproject.toml/poetry.lock. O que estava no `base.txt` e `production.txt` adicionei ao `[tool.poetry.dependencies]` e o que estava no `staging.txt` e `testing.txt` ao `[tool.poetry.dev-dependencies]`.

Alterei no `docker-compose.dev.gcp.yml` e o  `Makefile` de `python` para `python3`.

Configurei o Dockerfile e Dockerfile.ci para executar o poetry.

2022-02-01 01:45 UTC, GabrielRocha requested changes

2022-02-01 01:45 UTC, GabrielRocha commented on CHANGELOG.md
> -
Pq esse item foi removido do changelog?

2022-02-01 01:45 UTC, GabrielRocha commented on Dockerfile
> -ENV PATH="/opt/venv/bin:${PATH}"
Não tinha dado erro quando removemos essa ENV?

2022-02-01 01:45 UTC, GabrielRocha commented on cvat/pyproject.toml
> +authors = ["XXXX <xxxx@unico.io>"]
Pode colocar o email do squad.
check-liveness-engineering@unico.io

2022-02-01 12:53 UTC, camilasonoda commented on CHANGELOG.md
> -
Tinha removido errado, já voltei...

2022-02-01 12:56 UTC, camilasonoda commented on Dockerfile
> -ENV PATH="/opt/venv/bin:${PATH}"
Pensei que o erro era por causa disso, mas era outra coisa, corrigi, removi essa ENV e deu certo, sem erro.

2022-02-02 13:34 UTC, hspedro commented on Dockerfile
> +RUN pip install "poetry==$POETRY_VERSION"
nit: poderiamos instalar o `poetry` no `RUN` anterior que já é usado pra instalar as dependencias do Python. Dai moveria essas linhas pra antes da 44

2022-02-02 13:34 UTC, hspedro commented on Dockerfile
> +    fi
Não vale a pena criar um stage de build pra cada configuração do Django? Pode ser que eventualmente mais coisas precisem ser alteradas de testing/development/prod

2022-02-02 13:34 UTC, hspedro commented on Dockerfile.ci
> +RUN if [ "$DJANGO_CONFIGURATION" = "testing" ] || [ "$DJANGO_CONFIGURATION" = "development" ]; then \
Nesse Dockerfile estamos setando a env para `testing` (linha 3). Eu nem alteraria esse arquivo porque hoje ele não é usado, quando formos trocar/implementar o CI (github actions) podemos revisitar

2022-02-03 14:42 UTC, GabrielRocha commented on Dockerfile
> +    fi
Essa alteração será feita em outro PR

2022-02-03 14:52 UTC, vinicius-nogueira approved these changes
Revisado, passou nos testes unitários e no teste manual.

2022-02-03 14:53 UTC, merged