[CAP-27] Validate token csrf
acesso-io/techcore-cvat pull request #143
Opened 2022-02-07 13:47 UTC by camilasonoda

Validação do token CSRF apenas nas chamadas da api `/api/v1`, no django admin por exemplo não é mais validado o token.
O prefixo `/api/v1` agora é passado como variavel de ambiente.

Segue a evidencia da alteração:
https://user-images.githubusercontent.com/31012254/152799433-c7c6f4e5-8dfa-4dfd-af8d-9ebf82a74f8f.mp4

2022-02-07 14:31 UTC, GabrielRocha requested changes

2022-02-09 20:22 UTC, GabrielRocha approved these changes

2022-02-09 20:49 UTC, vinicius-nogueira commented on cvat/settings/base.py
> +URL_API = "/api/v1"
Pra mim aparece um warning aqui na revisão: "No new line at the end". Precisa ser resolvido?

2022-02-09 20:50 UTC, vinicius-nogueira commented on cvat/settings/middleware.py
> +import pdb
É necessário manter o `import pdb` no arquivo?

2022-02-09 20:51 UTC, vinicius-nogueira submitted a review, later dismissed

2022-02-09 21:19 UTC, GabrielRocha commented on cvat/settings/middleware.py
> +import pdb
Não é necessário!

2022-02-09 21:20 UTC, GabrielRocha requested changes
Remover o pdb e rodar o lint no PR

2022-02-10 12:28 UTC, vinicius-nogueira approved these changes
Done!

2022-02-10 13:28 UTC, GabrielRocha approved these changes

2022-02-10 13:41 UTC, merged