[CAP-39] Fix/remove completed task
acesso-io/techcore-cvat pull request #145
Opened 2022-02-15 13:28 UTC by camilasonoda

[backend] Alterei o `queryset` da `TaskViewSet` removendo as `tasks` com status `completed`.
[front] Ajuste no front para após a conclusão do job redirecinar para a lista de tasks.
[test] Adicionei um teste para verificar se após alteração do status de uma task esta é removida da lista de task.

2022-02-15 14:03 UTC, hspedro submitted a review, later dismissed

2022-02-15 19:55 UTC, GabrielRocha requested changes

2022-02-15 19:55 UTC, GabrielRocha commented on cvat/apps/engine/tests/test_rest_api.py
> +        with ForceLogin(self.user, self.client):
@camilasonoda 
Seria melhor vc quebrar os testes, pois em um único teste você está validando a criação da task, o status code, listagem, atualização e se task concluídas aparecem na listagem.

2022-02-16 17:19 UTC, camilasonoda commented on cvat/apps/engine/tests/test_rest_api.py
> +        with ForceLogin(self.user, self.client):
Tentei fazer os testes ( de cadastro da task, cadastro do job e alteração do status do job para completed)  separados mas a ordem de execução estava quebrando os testes. Por isso, criei o  `test_task_completed`  que chama os métodos de cadastro da task, cadastro do job e alteração do status do job.

2022-02-17 15:50 UTC, GabrielRocha commented on cvat/apps/engine/tests/test_rest_api.py
> +        with ForceLogin(self.user, self.client):
A minha sugestão é criar a task com o status `completed` direto na base de teste e realiza as consultas em testes individuais
```python
class TaskListAPITestCase(APITestCase):
    def setUp(self):
        self.client = APIClient()
        self.task_name = "my task #1"
        task_spec = {
            "name": "my task #99",
            "owner": self.user,
            "status": StatusChoice.COMPLETED,
            "overlap": 0,
            "segment_size": 100,
        }
        self.completed_task = Task.objects.create(**task_spec)
    ...
    
        def test_exclude_completed_tasks_from_list(self):
        with ForceLogin(self.admin, self.client):
            response = self.client.get(f"{settings.URL_API}/tasks")
        self.assertEquals(Task.objects.count(), 5)
        self.assertEquals(response.json()['count'], 4)
        task_ids = [task['id'] for task in response.json()['results']]
        self.assertNotIn(self.completed_task.id, task_ids)

    def test_should_return_404_for_completed_tasks(self):
        with ForceLogin(self.user, self.client):
            response = self.client.get(f"{settings.URL_API}/tasks/{self.completed_task.id}")
        self.assertEquals(response.status_code, 404)
```

2022-02-17 18:21 UTC, camilasonoda commented on cvat/apps/engine/tests/test_rest_api.py
> +        with ForceLogin(self.user, self.client):
Muito bom, não tinha pensado em inserir direto no banco e depois comparar a diferença com o retorno da api, assim fica melhor! Corrigido :grin:

2022-02-17 18:29 UTC, vinicius-nogueira approved these changes

2022-02-17 23:26 UTC, GabrielRocha approved these changes

2022-02-18 12:19 UTC, merged