Feat/service account token
acesso-io/techcore-cvat pull request #171
Opened 2022-03-25 20:42 UTC by camilasonoda

### Motivação e contexto:
Criação de fluxo para contas de serviços que utilizam scripts do projeto. Alteração importante pois a utilização do recaptcha no login acaba impactando na geração de lotes via script.

### Descrição da solução:
Foi adicionado ao gcp o secret ‘cvat-api-key’ contendo um hash. Este secret foi utilizado no LoginView para, caso houver, validar se o valor do X_API_KEY no header é igual ao ‘cvat-api-key’. Caso contrário é realizado a validação via recaptcha

### Testes:
- [X] Backend;
- [X] Frontend;
- [X] Interface;
- [ ] E2E.

### Links úteis:
[Jira](url)

2022-03-28 18:17 UTC, GabrielRocha requested changes

2022-03-28 18:17 UTC, GabrielRocha commented on ci/cloudbuild.yaml
> +  secretEnv: [ 'RECAPTCHA_SITE_KEY', 'X_API_KEY']
Não precisamos definir essa variável no processo de build, somente na execução via arquivo `.sh`

2022-03-28 22:33 UTC, GabrielRocha approved these changes

2022-03-30 14:35 UTC, vinicius-nogueira approved these changes

2022-03-30 18:43 UTC, GabrielRocha approved these changes

2022-03-30 19:14 UTC, merged