[CAP-221] Atualizar a versão da lib mistune para 2.0.3
acesso-io/techcore-cvat pull request #298
Opened 2022-07-25 13:56 UTC by vinicius-nogueira

Este PR visa atualizar a biblioteca mistune para a versão 2.0.3, por questões de vulnerabilidade encontrada pelo Snyk.

### Motivação e contexto:

Após a adição dos arquivos de configuração do Poetry via CLI na rotina de verificação do Snyk, algumas vulnerabilidades foram identificadas, havendo assim a necessidade da atualização das mesmas.

https://app.snyk.io/org/unico-check-liveness/project/666bf76f-031b-4bb2-bc7b-f6027c801794

### Descrição da solução:

Atualização realizada nos arquivos `pyproject.toml` e `poetry.lock` através do seguinte comando do Poetry, que não instala as dependências mas apenas atualiza o arquivo `poetry.lock`:

```sh
$ poetry update mistune --lock 
```

### Testes:

- [x] Backend;
- [x] Frontend;
- [x] Interface;

### Links úteis:
[Jira](https://unicoidtech.atlassian.net/browse/CAP-221)

2022-08-04 13:26 UTC, GabrielRocha requested changes

2022-08-04 13:26 UTC, GabrielRocha commented on cvat/pyproject.toml
> +mistune = ">=2.0.3"
Será que vai dar conflito com o PR https://github.com/acesso-io/techcore-cvat/pull/300

2022-08-05 18:22 UTC, vinicius-nogueira commented on cvat/pyproject.toml
> +mistune = ">=2.0.3"
Sim, já fiz uns testes aqui e deu erro, vou fazer o merge desse PR e atualizar o #300 com as alterações desse aqui, e resolvo as dependências lá.

2022-08-08 20:10 UTC, vinicius-nogueira commented on cvat/pyproject.toml
> +nbconvert = "7.0.0rc3"
O `nbconvert` não aceita a versão 2.0.3 do `mistune`, isso só é resolvido pelo `nbconvert` na versão de release candidate 7.0.0.

2023-01-24 03:53 UTC, closed without merging