[CLIV-30] - Change user ID to UUID in request API
acesso-io/techcore-cvat pull request #87
Opened 2021-12-09 15:04 UTC by vinicius-nogueira

Tarefa proposta pelo time de segurança para remover o ID sequencial da rota da API (`/api/v1/users/<id>`), por um ID único e não sequencial, UUID.

[CLIV-30](https://unicoidtech.atlassian.net/browse/CLIV-30)

2021-12-09 17:34 UTC, hs-pedro approved these changes

2021-12-09 17:34 UTC, hs-pedro commented on cvat/apps/engine/tests/test_rest_api.py
> +        response_assignee_username = response.data["assignee"]["username"] if response.data["assignee"] else None
nit: daria pra usar só o default: `response.data.get('assignee', {}).get('username')`

2021-12-09 17:46 UTC, GabrielRocha requested changes
Estou analisando a integração com o frontend.

2021-12-13 13:01 UTC, GabrielRocha commented on cvat/apps/engine/tests/test_rest_api.py
> +        response_assignee_username = response.data["assignee"]["username"] if response.data["assignee"] else None
Nesse caso nós não podemos utilizar o `get` pois o **response.data** tem uma key para `assignee` com o value `None` e daria o erro **AttributeError: 'NoneType' object has no attribute 'get'**
```
(Pdb) data = response.data.get('assignee', {})
(Pdb) data
(Pdb) data.get('username')
*** AttributeError: 'NoneType' object has no attribute 'get'
(Pdb)
```

2021-12-13 13:01 UTC, GabrielRocha submitted a review, later dismissed

2021-12-13 17:19 UTC, vinicius-nogueira commented
Testei atribuir um lote com meu _superuser_ para um usuário com permissão de anotador: 
![image](https://user-images.githubusercontent.com/58186122/145857990-e4091a95-c265-4f48-87f1-76bd3641b652.png)

Faço login no CVAT com esse usuário anotador e tento abrir o lote atribuído e dá esse erro:
![image](https://user-images.githubusercontent.com/58186122/145858484-bee770db-8b70-4f60-85b1-0084a6b9859c.png)

2021-12-13 20:18 UTC, vinicius-nogueira commented
- Teste na rota `http://localhost/api/v1/users`:
Não retorna mais a lista de usuários do sistema; **OK**

![image](https://user-images.githubusercontent.com/58186122/145881942-cdd290ff-1e0e-49f5-afd1-3e1fe3a2505a.png)

---
- Teste na rota `http://localhost/api/v1/users/<id>`:
Não retorna mais as informações do usuário pesquisando pelo id; **OK**

![image](https://user-images.githubusercontent.com/58186122/145881981-d6769aa9-d0aa-4bb5-ac9c-2d4a5c9e1ae7.png)

---
- Teste na rota `http://localhost/api/v1/users/<uuid>`:
Retorna as informações do usuário pesquisando pelo uuid do mesmo; **OK**

![image](https://user-images.githubusercontent.com/58186122/145882113-82ae85ef-ae45-4cb5-b616-d3ae49bd11d6.png)

2021-12-14 17:45 UTC, vinicius-nogueira commented
> * Testei atribuir um lote com meu _superuser_ para um usuário com permissão de anotador:
> 
> 
> * Faço login no CVAT com esse usuário anotador e tento abrir o lote atribuído e dá esse erro:
> 
> 
> * Se der F5 algumas vezes, ele acessa o lote.

Resolvido!

2021-12-14 20:37 UTC, GabrielRocha approved these changes

2021-12-14 22:06 UTC, merged