Fix/add re captcha CLIV-33
acesso-io/techcore-cvat pull request #88
Opened 2021-12-09 22:18 UTC by camilasonoda

2021-12-09 22:20 UTC, camilasonoda commented
Foi adicionado o reCAPTCHA na tela de login
![tela](https://user-images.githubusercontent.com/31012254/145484722-e8104c69-247e-48aa-995b-46b40f05b6b7.png)
Configurada a chave do reCaptcha para os domínios localhost e annotation.unico.io/, preciso adicionar outro domínio?
![site-recaptcha](https://user-images.githubusercontent.com/31012254/145484765-6bfc96a5-d311-4ff3-bad0-b6e6e75354a1.png)

Evidência do teste da api

![teste2](https://user-images.githubusercontent.com/31012254/145484815-a07dcbef-1abf-4912-81c7-a5c4ee4763af.png)

Teste do frontend

![teste1](https://user-images.githubusercontent.com/31012254/145484841-624124c5-9777-4b4d-b1ab-1b494e55520b.png)

2021-12-10 13:59 UTC, GabrielRocha commented on cvat/apps/authentication/views.py
> +    def validateReCaptcha(self, recaptchaResponse):
Seria legal adicionar um teste para o fluxo de token inválido.

2021-12-13 13:51 UTC, camilasonoda commented
Retirei o localhost

![recaptcha](https://user-images.githubusercontent.com/31012254/145824312-31c5c581-706b-4c25-9fee-8ad735db7152.png)

2021-12-13 13:52 UTC, camilasonoda commented on cvat/apps/authentication/views.py
> +    def validateReCaptcha(self, recaptchaResponse):
oks, adicionei o teste :)

2021-12-13 14:37 UTC, GabrielRocha requested changes

2021-12-13 14:37 UTC, GabrielRocha commented on cvat/apps/authentication/views.py
> +        reCaptchaValidated = self.validateReCaptcha(request.POST.get('reCaptchaToken'))
[Typo] - Segundo a PEP8 nós devemos usar `snake_case` para as variáveis
https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

2021-12-13 15:08 UTC, camilasonoda commented on cvat/apps/authentication/views.py
> +        reCaptchaValidated = self.validateReCaptcha(request.POST.get('reCaptchaToken'))
Ajustei os nomes das variaveis e rodei os testes novamente.

2021-12-13 16:08 UTC, GabrielRocha approved these changes

2021-12-13 17:23 UTC, merged